### ISSUE TITLE
Module not found: Can't resolve 'react-native' in '/node_modules/react-gifted-chat/dist'

### ISSUE THREAD

**Issue by tristanyong** [batuhansahan/react-gifted-chat#1]
#### Issue Description
Error of Module not found: Can't resolve 'react-native' in 'node_modules/react-gifted-chat/dist'
keeps appearing
#### Steps to Reproduce / Code Snippets

Installing the dependency normally.
Running on Nextjs for React.

#### Expected Results

Error will be shown on initialisation

#### Additional Information

* Nodejs version: v8.12.0
* React version: v16.9.0
* react-gifted-chat version: v1.0.5
* Browser(s) (Chrome, etc.): Chrome

**Comment by batuhansahan** [comment]
You should use https://github.com/FaridSafi/react-native-gifted-chat/blob/master/README.md#react-native-web

**Comment by batuhansahan** [comment]
Done
