### ISSUE TITLE
renderChatFooter gets rendered row wise with MessageContainer

### ISSUE THREAD

**Issue by uyogesh** [batuhansahan/react-gifted-chat#3]
#### Issue Description

renderChatFooter props is rendered side by side with the MessagesContainer component. 

#### Steps to Reproduce / Code Snippets
[https://i.imgur.com/oxa4pB9.png](url)

`<GiftedChat
            messages={messages}
            onSend={(messages) => onSend(messages)}
            ref={(ref) => {
                giftedChatRef = ref
            }}
            renderChatFooter={() => {
                return (
                    <div>
                        <p>SomeOne is Typing</p>
                    </div>
                )
            }}/>`
Just pass renderChatFooter props to GiftedChat Component. The passed component wont be rendered on the Footer as the name suggests, it'll be placed on side of the MessageContainer. 

#### Expected Results

[https://i.imgur.com/LugieKt.png](url)

#### Additional Information

* Nodejs version: v12.2.0
* React version: ^16.10.1
* react-gifted-chat version: ^1.0.5
* Browser(s) (Chrome, etc.): Chrome, Mozilla Firefox

**Comment by batuhansahan** [comment]
This repository is no longer maintained.
You should use https://github.com/FaridSafi/react-native-gifted-chat/blob/master/README.md#react-native-web
