### ISSUE TITLE
Can't resolve 'react-native'

### ISSUE THREAD

**Issue by krishna-mastree** [batuhansahan/react-gifted-chat#4]
#### Issue Description

Can't resolve 'react-native' in '/Users/krishnamudhiraj/Projects/mastree-ono-platform/node_modules/react-gifted-chat/dist'

#### Steps to Reproduce / Code Snippets

install the component npm install react-gifted-chat --save
import the component with import { GiftedChat } from 'react-gifted-chat'
there is Error:

Can't resolve 'react-native' in '/Users/krishnamudhiraj/Projects/mastree-ono-platform/node_modules/react-gifted-chat/dist'

#### Expected Results

the error should not be there

#### Additional Information

* Nodejs version: 12.14.1
* React version: 16.9.0
* react-gifted-chat version: ^1.0.5
* Browser(s) (Chrome, etc.): Chrome

**Comment by batuhansahan** [comment]
You should use https://github.com/FaridSafi/react-native-gifted-chat/blob/master/README.md#react-native-web
